import Head from "next/head";
import Image from "next/image";
import styles from "@/src/styles/Home.module.css";
import featuredImage from "@/public/home-featured-image.svg";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav>
        <span>Oluwatobi</span>
        <span>
          <span>Milestones</span>
          <span>Press</span>
          <span>Awards</span>
          <span className="theme">th</span>
        </span>
      </nav>
      <section className={styles.featuredSection}>
        <h1>Oluwatobi Sofela</h1>
        <p>A JavaScript Front End Web Developer</p>
        <Image src={featuredImage} alt="Home featured image" />
      </section>
    </>
  );
}
