import Head from "next/head";
import Image from "next/image";
import transformProjPic from "@/public/transform-oluwatobi-sofela.png";
import findProjPic from "@/public/find-oluwatobi-sofela.png";
import youtubeProjPic from "@/public/youtube-clone-oluwatobi-sofela.png";
import styles from "@/src/styles/Home.module.css";
import { Nunito } from "next/font/google";

const nunito = Nunito({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav className={nunito.className}>
        <span>Oluwatobi</span>
        <span>
          <span>Milestones</span>
          <span>Press</span>
          <span>Awards</span>
          <span className="theme">th</span>
        </span>
      </nav>
      <section className={styles.introSection}>
        <div>
          <h1>Oluwatobi Sofela</h1>
          <p className={nunito.className}>
            A JavaScript Front End Web Developer
          </p>
        </div>
      </section>
      <section className={styles.projectSection}>
        <h2>Selected Projects</h2>
        <div>
          <span className={styles.infoSpan}>
            <h3>Transform.</h3>
            <small>ReactJS, React Router</small>
            <p className={nunito.className}>
              Transform is a shopping cart website where users browse for
              glamorous items to spark up their style. You can use it to
              transform your clothing, jewelry, and electronic collections.
            </p>
          </span>
          <span className={styles.imageSpan}>
            <Image
              src={transformProjPic}
              alt="Transform shopping cart project"
              placeholder="blur"
            />
          </span>
        </div>
        <div>
          <span className={styles.infoSpan}>
            <h3>Find</h3>
            <small>Firebase, Jest, ReactJS, Testing Library</small>
            <p className={nunito.className}>
              Where is Waldo is a search-and-find game where a player searches
              an image for some items (e.g., Waldo, Cat, Apple, etc.). You
              finish the game by finding all the specified elements.
            </p>
          </span>
          <span className={styles.imageSpan}>
            <Image src={findProjPic} alt="Find project" placeholder="blur" />
          </span>
        </div>
        <div>
          <span className={styles.infoSpan}>
            <h3>YouTube Clone</h3>
            <small>Firebase, Jest, ReactJS, Testing Library</small>
            <p className={nunito.className}>
              YouTube Clone is a replication of the YouTube website. This
              replica implements most of the live website's functionality, like
              authentication, search, history, and shorts. So, you can use it to
              watch your favorite videos just as you would with the actual
              website.
            </p>
          </span>
          <span className={styles.imageSpan}>
            <Image
              src={youtubeProjPic}
              alt="Youtube project"
              placeholder="blur"
            />
          </span>
        </div>
      </section>
    </>
  );
}
